# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_A/joint_trajectory_controller
    - arm_B/joint_trajectory_controller
    - arm_A/scaled_joint_trajectory_controller
    - arm_B/scaled_joint_trajectory_controller

  ur_A/joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - arm_A_ur_shoulder_pan_joint
      - arm_A_ur_shoulder_lift_joint
      - arm_A_ur_elbow_joint
      - arm_A_ur_wrist_1_joint
      - arm_A_ur_wrist_2_joint
      - arm_A_ur_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  ur_B/joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - arm_B_ur_shoulder_pan_joint
      - arm_B_ur_shoulder_lift_joint
      - arm_B_ur_elbow_joint
      - arm_B_ur_wrist_1_joint
      - arm_B_ur_wrist_2_joint
      - arm_B_ur_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  ur_A/scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - arm_A_ur_shoulder_pan_joint
      - arm_A_ur_shoulder_lift_joint
      - arm_A_ur_elbow_joint
      - arm_A_ur_wrist_1_joint
      - arm_A_ur_wrist_2_joint
      - arm_A_ur_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: false
  ur_B/scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - arm_B_ur_shoulder_pan_joint
      - arm_B_ur_shoulder_lift_joint
      - arm_B_ur_elbow_joint
      - arm_B_ur_wrist_1_joint
      - arm_B_ur_wrist_2_joint
      - arm_B_ur_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: false