# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ur_A_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    ur_B_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ur_A_controller:
  ros__parameters:
    joints:
      - arm_A_ur_shoulder_pan_joint
      - arm_A_ur_shoulder_lift_joint
      - arm_A_ur_elbow_joint
      - arm_A_ur_wrist_1_joint
      - arm_A_ur_wrist_2_joint
      - arm_A_ur_wrist_3_joint
    command_interfaces:
      []
    state_interfaces:
      []
ur_B_controller:
  ros__parameters:
    joints:
      - arm_B_ur_shoulder_pan_joint
      - arm_B_ur_shoulder_lift_joint
      - arm_B_ur_elbow_joint
      - arm_B_ur_wrist_1_joint
      - arm_B_ur_wrist_2_joint
      - arm_B_ur_wrist_3_joint
    command_interfaces:
      []
    state_interfaces:
      []